services:
  - type: web
    name: store-back
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://store-front.onrender.com

  - type: pserv
    name: ecommerce-mongodb
    env: docker
    region: oregon
    plan: free
    ipAllowList: []
